FROM n8nio/n8n:stable

# If install a external npm package...

# USER root
# RUN mkdir -p /home/node/.n8n/modules && chown -R node:node /home/node/.n8n
# 
# USER node
# WORKDIR /home/node/.n8n/modules
# RUN npm init -y && npm install --omit=dev zod
